[package]
name = "compare-rust-go-channels"
version = "0.1.0"
authors = ["Ram√≥n Berrutti <ramonberrutti@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
